vim.opt.guicursor = "" -- Block cursor in insert mode
vim.g.mapleader = " "
vim.g.maplocalleader = ","  -- For vimtex
vim.opt.smartindent = true
vim.opt.relativenumber = true
vim.opt.nu = true
vim.opt.showmode = false
vim.opt.scrolloff = 20
vim.o.shell = "/usr/bin/zsh"
vim.opt.textwidth = 79
vim.opt.conceallevel = 1
vim.o.termguicolors = true
vim.indent_type = "Spaces"
vim.indent_width = 2
vim.column_width = 120
vim.tabstop = 2
vim.shiftwidth = 2
vim.opt_local.expandtab = true
